# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\00stereo_camera\SpatialDetection_depth1119button\01ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1345, 921)
        Form.setMinimumSize(QtCore.QSize(700, 440))
        Form.setMaximumSize(QtCore.QSize(1500, 1300))
        Form.setStyleSheet("background:rgb(139, 139, 139)")
        self.label2_2 = QtWidgets.QLabel(Form)
        self.label2_2.setGeometry(QtCore.QRect(440, 20, 451, 91))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(27)
        font.setBold(True)
        self.label2_2.setFont(font)
        self.label2_2.setStyleSheet("QLabel{background-color:rgb(37, 37, 37)}")
        self.label2_2.setObjectName("label2_2")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(80, 140, 601, 411))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox::title{\n"
"font-size: 72px;\n"
"font-weight: bold;\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.disconnect = QtWidgets.QPushButton(self.groupBox)
        self.disconnect.setGeometry(QtCore.QRect(400, 130, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.disconnect.setFont(font)
        self.disconnect.setStyleSheet("QPushButton {\n"
"background-color:rgb(255, 255, 255)；\n"
"}")
        self.disconnect.setObjectName("disconnect")
        self.connect = QtWidgets.QPushButton(self.groupBox)
        self.connect.setGeometry(QtCore.QRect(400, 70, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.connect.setFont(font)
        self.connect.setStyleSheet("QPushButton {\n"
"background-color:rgb(255, 255, 255)；\n"
"}")
        self.connect.setObjectName("connect")
        self.query = QtWidgets.QPushButton(self.groupBox)
        self.query.setGeometry(QtCore.QRect(400, 190, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.query.setFont(font)
        self.query.setStyleSheet("QPushButton {\n"
"background-color:rgb(255, 255, 255)；\n"
"}")
        self.query.setObjectName("query")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(20, 70, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("")
        self.comboBox.setObjectName("comboBox")
        self.restatus = QtWidgets.QTextEdit(self.groupBox)
        self.restatus.setGeometry(QtCore.QRect(0, 130, 351, 281))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.restatus.setFont(font)
        self.restatus.setStyleSheet("")
        self.restatus.setObjectName("restatus")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(700, 140, 551, 761))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("QGroupBox::title{\n"
"font-size: 72px;\n"
"font-weight: bold;\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.bt_close = QtWidgets.QPushButton(self.groupBox_2)
        self.bt_close.setGeometry(QtCore.QRect(320, 70, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.bt_close.setFont(font)
        self.bt_close.setStyleSheet("QPushButton {\n"
"background-color:rgb(255, 255, 255)；\n"
"}")
        self.bt_close.setObjectName("bt_close")
        self.bt_start = QtWidgets.QPushButton(self.groupBox_2)
        self.bt_start.setGeometry(QtCore.QRect(110, 70, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.bt_start.setFont(font)
        self.bt_start.setStyleSheet("QPushButton {\n"
"background-color:rgb(255, 255, 255)；\n"
"}")
        self.bt_start.setObjectName("bt_start")
        self.lab_show = QtWidgets.QLabel(self.groupBox_2)
        self.lab_show.setGeometry(QtCore.QRect(70, 200, 416, 416))
        self.lab_show.setMinimumSize(QtCore.QSize(416, 416))
        self.lab_show.setMaximumSize(QtCore.QSize(416, 416))
        self.lab_show.setText("")
        self.lab_show.setObjectName("lab_show")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(80, 570, 601, 331))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("QGroupBox::title{\n"
"font-size: 72px;\n"
"font-weight: bold;\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.groupBox_3.setObjectName("groupBox_3")
        self.btQscram = QtWidgets.QPushButton(self.groupBox_3)
        self.btQscram.setGeometry(QtCore.QRect(370, 120, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.btQscram.setFont(font)
        self.btQscram.setStyleSheet("QPushButton {\n"
"background-color:rgb(255, 255, 255)；\n"
"}")
        self.btQscram.setObjectName("btQscram")
        self.btFscram = QtWidgets.QPushButton(self.groupBox_3)
        self.btFscram.setGeometry(QtCore.QRect(370, 170, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.btFscram.setFont(font)
        self.btFscram.setStyleSheet("QPushButton {\n"
"background-color:rgb(255, 255, 255)；\n"
"}")
        self.btFscram.setObjectName("btFscram")
        self.btResetscram = QtWidgets.QPushButton(self.groupBox_3)
        self.btResetscram.setGeometry(QtCore.QRect(370, 270, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.btResetscram.setFont(font)
        self.btResetscram.setStyleSheet("QPushButton {\n"
"background-color:rgb(255, 255, 255)；\n"
"}")
        self.btResetscram.setObjectName("btResetscram")
        self.btSetscram = QtWidgets.QPushButton(self.groupBox_3)
        self.btSetscram.setGeometry(QtCore.QRect(370, 220, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.btSetscram.setFont(font)
        self.btSetscram.setStyleSheet("QPushButton {\n"
"background-color:rgb(255, 255, 255)；\n"
"}")
        self.btSetscram.setObjectName("btSetscram")
        self.btZscram = QtWidgets.QPushButton(self.groupBox_3)
        self.btZscram.setGeometry(QtCore.QRect(370, 70, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.btZscram.setFont(font)
        self.btZscram.setStyleSheet("QPushButton {\n"
"background-color:rgb(255, 255, 255)；\n"
"}")
        self.btZscram.setObjectName("btZscram")
        self.btrelZscram = QtWidgets.QPushButton(self.groupBox_3)
        self.btrelZscram.setGeometry(QtCore.QRect(60, 70, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.btrelZscram.setFont(font)
        self.btrelZscram.setStyleSheet("QPushButton {\n"
"background-color:rgb(255, 255, 255)；\n"
"}")
        self.btrelZscram.setObjectName("btrelZscram")
        self.btQ = QtWidgets.QPushButton(self.groupBox_3)
        self.btQ.setGeometry(QtCore.QRect(60, 120, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.btQ.setFont(font)
        self.btQ.setStyleSheet("QPushButton {\n"
"background-color:rgb(255, 255, 255)；\n"
"}")
        self.btQ.setObjectName("btQ")
        self.btF = QtWidgets.QPushButton(self.groupBox_3)
        self.btF.setGeometry(QtCore.QRect(60, 170, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.btF.setFont(font)
        self.btF.setStyleSheet("QPushButton {\n"
"background-color:rgb(255, 255, 255)；\n"
"}")
        self.btF.setObjectName("btF")
        self.btSet = QtWidgets.QPushButton(self.groupBox_3)
        self.btSet.setGeometry(QtCore.QRect(60, 220, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.btSet.setFont(font)
        self.btSet.setStyleSheet("QPushButton {\n"
"background-color:rgb(255, 255, 255)；\n"
"}")
        self.btSet.setObjectName("btSet")
        self.btReset = QtWidgets.QPushButton(self.groupBox_3)
        self.btReset.setGeometry(QtCore.QRect(60, 270, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.btReset.setFont(font)
        self.btReset.setStyleSheet("QPushButton {\n"
"background-color:rgb(255, 255, 255)；\n"
"}")
        self.btReset.setObjectName("btReset")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label2_2.setText(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'华文行楷\'; font-size:48pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei UI\'; font-size:36pt; font-weight:700; color:#ffffff;\">视觉引导系统</span></p></body></html>"))
        self.groupBox.setTitle(_translate("Form", "数据库查询"))
        self.disconnect.setText(_translate("Form", "断开"))
        self.connect.setText(_translate("Form", "连接"))
        self.query.setText(_translate("Form", "查询"))
        self.groupBox_2.setTitle(_translate("Form", "视觉识别"))
        self.bt_close.setText(_translate("Form", "关闭"))
        self.bt_start.setText(_translate("Form", "开启"))
        self.groupBox_3.setTitle(_translate("Form", "控制指令"))
        self.btQscram.setText(_translate("Form", "取工具急停"))
        self.btFscram.setText(_translate("Form", "放工具急停"))
        self.btResetscram.setText(_translate("Form", "复位急停"))
        self.btSetscram.setText(_translate("Form", "置位急停"))
        self.btZscram.setText(_translate("Form", "总急停"))
        self.btrelZscram.setText(_translate("Form", "总急停释放"))
        self.btQ.setText(_translate("Form", "取工具"))
        self.btF.setText(_translate("Form", "放工具"))
        self.btSet.setText(_translate("Form", "置位"))
        self.btReset.setText(_translate("Form", "复位"))
